# vim ft=yaml

# After changing this file, check it on:
#   http://yaml-online-parser.appspot.com/

build:
  # https://github.com/Shippable/support/issues/3873
  ci:
    - echo $CI_REPORTS && mkdir -p $CI_REPORTS
    - echo $COVERAGE_REPORTS && mkdir -p $COVERAGE_REPORTS

env:
  global:
    - CI_REPORTS=shippable/testresults
    - COVERAGE_REPORTS=shippable/codecoverage
    - DISPLAY=""

language: python

sudo: true

python:
  - 2.7
  - 3.6

cache: pip

before_install:
  - apt-get update --fix-missing
  - apt-get install freetype*
  - apt-get install python-dev python-tk python3-tk
  - apt-get install pkg-config
  - pip install --upgrade pip
  - gcc --version ; python --version ; pip --version ; pwd ; ls -l

install:
  - pip install -r requirements.txt
  - pip install "nose>=1.3.7" coverage codecov "pytest>=3.0.5" flake8
  - pip list

script:
  - unset DISPLAY
  - mkdir results
  - python setup.py check -m -s
  # - nosetests --with-xunit --xunit-file=shippable/testresults/nosetests.xml
  - nosetests bpdl -v --exe --with-doctest --with-coverage --cover-package=bpdl
  - python experiments/run_dataset_generate.py --nb_samples 25 --nb_patterns 2 --image_size 64 64
  - python experiments/run_dataset_add_noise.py -p ./data_images
  - nosetests experiments -v --exe --with-doctest --with-xunit --xunit-file=shippable/testresults/nosetests.xml
  - flake8 . --ignore=E402,E731 --max-line-length=100

  - rm -rf results && mkdir results
  # EXPERIMENTS: pre-processing
  - python experiments/run_cut_minimal_images.py -i "./data_images/imaginal_discs/gene/*.png" -o ./data_images/imaginal_discs/gene_cut
  - python experiments/run_extract_fuzzy_activation.py -i "./data_images/ovary_stage-2/image/*.png" -o ./data_images/ovary_stage-2/gene
  - python experiments/run_extract_fuzzy_activation.py -i "./data_images/ovary_stage-3/image/*.png" -o ./data_images/ovary_stage-3/gene

  # EXPERIMENTS: core
  - python experiments/run_experiments.py --type synth -i ./data_images/syntheticDataset_vX -o ./results -c ./data_images/sample_config.json
  - python experiments/run_experiments.py --type real -i ./data_images/imaginal_discs -o ./results --dataset gene_small --nb_workers 2
  - python experiments/run_reconstruction.py -e ./results/ExperimentBPDL_real_imaginal_discs_gene_small --visual

  # EXPERIMENTS: post-processing
  - python experiments/run_parse_experiments_result.py -i ./results -r results.csv
  - python experiments/run_recompute_experiments_result.py -i ./results
  - python experiments/run_parse_experiments_result.py -i ./results -r results_NEW.csv
  # - codecov

after_success:
  - python setup.py install

  - codecov -t 9507eeee-6a1e-4313-87fa-f73064c539c9
  - coverage xml -o $COVERAGE_REPORTS/coverage.xml
  - coverage report
