# vim ft=yaml

# After changing this file, check it on:
#   http://yaml-online-parser.appspot.com/

# See doc/travis_notes.txt for some guidelines

language: python

sudo: false

python:
  - 2.7

# See http://docs.travis-ci.com/user/caching/#pip-cache
cache: pip

before_install:
#  - pip install .
  - pip install --upgrade pip

install:
  - pip install -r requirements.txt
  - pip install nose codecov
  - mkdir libs && cd libs && git clone https://github.com/Borda/pyGCO.git
  - cd pyGCO && pip install -r requirements.txt && python setup.py install
  - cd .. && rm -r pyGCO

script:
  - python experiments/run_generate_dataset.py --nb_samples 50 --nb_patterns 2
  - nosetests --with-doctest --with-coverage --cover-package=apdl,experiments

after_success:
  - codecov --token=9507eeee-6a1e-4313-87fa-f73064c539c9
  - coverage report
