# vim ft=yaml

# After changing this file, check it on:
#   http://yaml-online-parser.appspot.com/

# See doc/travis_notes.txt for some guidelines

dist: xenial  # Ubuntu 16.04

env:
  global:
    - CODACY_PROJECT_TOKEN=42d27066ead74eee9a090cae97328777

language: python

sudo: false

python:
  - 2.7
  # - 3.4  # will be deprecated for pandas
  - 3.6
  - 3.7
  - 3.8

# See http://docs.travis-ci.com/user/caching/#pip-cache
cache: pip

before_install:
  - pip install --upgrade pip
  - gcc --version ; python --version ; pip --version ; pwd ; ls -l

install:
  - pip install -r requirements.txt
  - pip install nose coverage codecov pytest codacy-coverage check-manifest flake8
  - pip list

before_script:
  - mkdir results
#  - python setup.py build_ext --inplace
  - check-manifest
  - python setup.py check -m -s

script:
  - unset DISPLAY
  - nosetests bpdl -v --exe --with-doctest --with-xunit --with-coverage --cover-package=bpdl
  - python experiments/run_dataset_generate.py --nb_samples 25 --nb_patterns 2 --image_size 64 64
  - nosetests experiments -v --exe --with-doctest --with-xunit
  - flake8 . --ignore=E402,E731 --max-line-length=100

after_success:
  - python setup.py install --user
  - codecov  # public repository on Travis CI
  - coverage xml
  - python-codacy-coverage -r coverage.xml
  - coverage report
