# vim ft=yaml

# After changing this file, check it on:
#   http://yaml-online-parser.appspot.com/

# See doc/travis_notes.txt for some guidelines

env:
  global:
    - CODACY_PROJECT_TOKEN=42d27066ead74eee9a090cae97328777

language: python

sudo: false

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

# See http://docs.travis-ci.com/user/caching/#pip-cache
cache: pip

before_install:
  - pip install --upgrade pip
  - mkdir libs

install:
  - root=$PWD
#  - cd $root/libs && git clone https://github.com/Borda/pyGCO.git
#  - cd $root/libs/pyGCO && pip install -r requirements.txt
#  - cd $root/libs/pyGCO && python setup.py install
#  - rm -r -f $here/libs/pyGCO
  - cd $root

  - pip install -r requirements.txt
  - pip install nose>=1.3.7 coverage codecov pytest>=3.0.5 codacy-coverage

before_script:
  - mkdir results
#  - python setup.py build_ext --inplace

script:
  - nosetests bpdl -v --exe --with-doctest --with-coverage --cover-package=bpdl
  - python experiments/run_dataset_generate.py --nb_samples 25 --nb_patterns 2 --image_size 64 64
  - nosetests experiments -v --exe --with-doctest --with-xunit

after_success:
  - python setup.py install
#  - codecov  # public repository on Travis CI
  # private repository on Travis CI
  - codecov -t 9507eeee-6a1e-4313-87fa-f73064c539c9
  - coverage xml
  - python-codacy-coverage -r coverage.xml
  - coverage report
