# unsigned integer
nb_labels: 7

# INIT type options:
#    'GT', 'GT-deform',
#    'random', 'random-grid',
#    'random-mosaic', 'random-mosaic-1.5', 'random-mosaic-2',
#    'greedy-GaussWS', 'greedy-OtsuWS', 'greedy-OtsuWS-rand',
#    'soa-init-NFM', 'soa-init-ICA', 'soa-init-PCA', 'soa-init-DL',
#    'soa-tune-NFM', 'soa-tune-ICA', 'soa-tune-PCA', 'soa-tune-DL'
init_tp:
  - 'random'

# used 4 or 8 connected neighborhood
connect_diag:
  - true
  - false

overlap_major: true

gc_reinit: true

ptn_compact: false

force_bg: false

# positive float
gc_regul: 0.000000001

# positive float
tol: 0.001

# unsigned integer
max_iter: 25

# positive float or null
deform_coef: [null, 0.0, 1.0, 0.5, 0.25]

# unsigned integer
runs: 1
