name: CI experiments

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:  # Trigger the workflow on push or pull request, but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, reopened, ready_for_review, synchronize]

jobs:

  bash-expt:
    if: github.event.pull_request.draft == false
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        python-version: [3.7, 3.9]

    # Timeout: https://stackoverflow.com/a/59076067/4521646
    timeout-minutes: 35

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: install BPDL
      run: |
        python --version
        pip --version
        pip list
        pip install -r requirements.txt
        pip install .
        rm -rf imsegm

    - name: Experiments (pre-processing)
      env:
        DISPLAY: ""
      run: |
        rm -rf results && mkdir results
        python experiments/run_cut_minimal_images.py -i "./data_images/imaginal_discs/gene/*.png" -o ./data_images/imaginal_discs/gene_cut
        python experiments/run_extract_fuzzy_activation.py -i "./data_images/ovary_stage-2/image/*.png" -o ./data_images/ovary_stage-2/gene
        python experiments/run_extract_fuzzy_activation.py -i "./data_images/ovary_stage-3/image/*.png" -o ./data_images/ovary_stage-3/gene

    - name: Experiments (main body)
      env:
        DISPLAY: ""
      run: |
        python experiments/run_experiments.py --type synth -i ./data_images/syntheticDataset_vX -o ./results -c ./data_images/sample_config.yml
        python experiments/run_experiments.py --type real -i ./data_images/imaginal_discs -o ./results --dataset gene_small --nb_workers 2
        python experiments/run_reconstruction.py -e ./results/ExperimentBPDL_real_imaginal_discs_gene_small --visual

    - name: Experiments (post-processing)
      env:
        DISPLAY: ""
      run: |
        python experiments/run_parse_experiments_result.py -i ./results -r results.csv
        python experiments/run_recompute_experiments_result.py -i ./results
        python experiments/run_parse_experiments_result.py -i ./results -r results_NEW.csv
